apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-app
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
