apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  serviceName: redis-server
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: "/var/lib/redis/redis-data"
          name: redis-data
        - mountPath: "/var/lib/redis/redis-conf"
          name: redis-config
        resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-claim
      - name: redis-conf
        configMap:
          name: redis-config
